services:
  db:
    image: postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  test:
    build: .
    command: ["python", "manage.py", "test"]
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env

  web:
    build: .
    command: sh -c "python manage.py create_superuser_if_needed &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - test
    volumes:
      - .:/app
    env_file:
      - ./.env

volumes:
  postgres_data: